### ISSUE TITLE
项目打不开

### ISSUE THREAD

**Issue by iyibo** [jiangyongjian/JYJ-#1]
代码不完整吗？AFNetworking没有？需要添加的库文件有哪些方便说下么，建议最好在readme里说明下

**Comment by jiangyongjian** [comment]
你会用cocoapods吗？你可以联系我啊，不会的话，就直接下载第三方框架，拖到项目中。

**Comment by iyibo** [comment]
@jiangyongjian  多谢提醒，可以了
